check current directory

diff --git a/installer/templates/install.sh.erb b/installer/templates/install.sh.erb
--- a/installer/templates/install.sh.erb
+++ b/installer/templates/install.sh.erb
@@ -149,6 +149,13 @@ function abort() {
     exit $status
 }
 
+function check_current_directory() {
+    if ! pwd | grep -q -E '^/tmp'; then
+	echo "You must extract installer in /tmp. Aborting"
+	exit 1
+    fi
+}
+
 function checkroot() {
     if test `id -u` -ne 0; then
 	echo "This installer must be run with administrator privileges. Aborting"
@@ -260,6 +267,7 @@ fi
 test $log && echo "Start: $(LC_ALL=C date)" 1>&$log
 test $log && chmod 0666 install.log
 
+check_current_directory
 checkroot
 prepare_user
 
